### ISSUE TITLE
Decide on frontend framework

### ISSUE THREAD

**Issue by synap5e** [overtrack-gg/owl-clips#2]

**Comment by benolot** [comment]
D...does it need one?

**Comment by synap5e** [comment]
I knew I should have named this issue differently but I couldn't think of what to call it 😝...

No framework is fine as long as we get something maintainable and easy to work with.
Suggestions for how to structure the frontend (and rename this issue) are good here too ☺️

**Comment by teamcoltra** [comment]
I would argue for server side scripting and maybe even have a database. It would kinda move this project away from being a public github project though (or could, but it would be fairly involved setting up your own version of the site).

**Comment by jess-sio** [comment]
If it is done with server side scripting and a database then only really the database would need to be private. The server would just need to be pointed towards the database. We could provide the option to generate a temporary example SQLite database when starting the server to make it easier for people helping with the system.

**Comment by synap5e** [comment]
Database access will be REST or maybe graphql, so this project is intended to be the user facing display of the data. #1 is about deciding on exactly the schema/method of accessing the database that this project will use.

The repo can also serve as a documentation for the API usage, but the API server code itself will (at least for now) stay private as it is fully dependent on other overtrack serverside code, so it's kinda useless without that, although I might post the model definitions and the like because no reason not to.

If speed becomes an issue (i.e. because this site has to talk to an HTTP API to get data), I could look into using the database directly by the site, but that makes it harder for others to run the site locally for development.

**Comment by synap5e** [comment]
@benolot Not sure what you have decided on, but this is in your hands now 😝

**Comment by benolot** [comment]
*evil laughter and hand rubbing*

**Comment by benolot** [comment]
Going with Laravel (PHP) to build the frontend - See the branch.
