### ISSUE TITLE
What If OWL Clips Is Just An API Reference?

### ISSUE THREAD

**Issue by teamcoltra** [overtrack-gg/owl-clips#3]
Tying into my other comment on #2 what if this repo is just an API reference document to how to grab the clips and then people can set up their own websites and the license agreement is to link back to Overtrack?

**Comment by synap5e** [comment]
I don't really see the need for multiple sites using the clips database, so this repo was intended as the "one true" website using the API. If there are new features people want in the site, I'd rather they PR changes to this one.

**Comment by teamcoltra** [comment]
There would be tons of other uses for the API. Overwatch League fan pages might serve clips from their favourite teams as a quick example off the top of my head. Gaming news agencies might want to keep a feed for either public or internal uses. 

:) It could then also be a private site which we build on here or elsewhere but also a platform for anyone to use the tech and then provide linkbacks.

**Comment by synap5e** [comment]
Documentation/API reference will be added as part of #4
